apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycj
spec:
  jobTemplate:
    metadata:
      name: mycj
    spec:
      template:
        spec:
          containers:
          - command: ["/bin/echo", "hello", "cj"]
            image: busybox
            name: mycj
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
