apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
      ## use ENV VAR directly
      - env:
        - name: YFOOD
          valueFrom: 
            configMapKeyRef: 
              key: food
              name: my-cm
        command:
        - "/bin/sh"
        - "-c"
        - "sleep 1000 && echo done"
        image: busybox
        name: myjob
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
